import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/front/Footer";
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* Main content */}
        <CartProvider>
        <main className="flex-grow">{children}</main>
        </CartProvider>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
